![在这里插入图片描述](https://img-blog.csdnimg.cn/87af7ebc2d6b49b281a1d79375443935.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)
- 程序出现error，则程序直接挂掉，没办法通过异常机制解决。
程序出现异常，可以通过异常机制来解决问题，使得程序继续执行。



- 运行时异常：
编译异常：
![在这里插入图片描述](https://img-blog.csdnimg.cn/88e6d458e88f4642a5e5757d3a3a4c13.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)

- 异常处理的作用：保证程序在出现异常之后还能继续执行
![在这里插入图片描述](https://img-blog.csdnimg.cn/f06ec515146b450a9806f9653e55c72b.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)


- 编译异常必须处理，运行异常可以不处理。因为系统会默认用throws处理。













## try-catch的处理方式
![在这里插入图片描述](https://img-blog.csdnimg.cn/b7cf0efbbe1d4a5f832267c26d59db4f.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)
快捷键:ctrl+alt+t



![ ](https://img-blog.csdnimg.cn/d618deb9b83b4ddcb8ca1e8ff9ffa7e9.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)![在这里插入图片描述](https://img-blog.csdnimg.cn/b9872792938d40519acce22361c3dab6.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)

![在这里插入图片描述](https://img-blog.csdnimg.cn/0de20cd16d304461a829b9add9a89409.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)
![在这里插入图片描述](https://img-blog.csdnimg.cn/849d82592c0640598c8fcba26249d6b5.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)
==例子==
![在这里插入图片描述](https://img-blog.csdnimg.cn/fa8dc2ece60140778d9b0cd75539354f.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)




![在这里插入图片描述](https://img-blog.csdnimg.cn/87253fcc614c49e0b0fdf8b01a13954d.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)
![在这里插入图片描述](https://img-blog.csdnimg.cn/c6f5ee3b4ebb4c0194441c22cff8d788.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)


## throws的处理方式
![在这里插入图片描述](https://img-blog.csdnimg.cn/eb802db749c340daa38bc7cbf6f53e10.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)
方法的调用者一般是其他方法：比如在主方法中使用其他类的方法，那么这个主方法就是调用者。




- ![在这里插入图片描述](https://img-blog.csdnimg.cn/4333c1b36c0b4ffcb876703367d48801.png)
![在这里插入图片描述](https://img-blog.csdnimg.cn/755d4605ec924a50a722dd33fbfb62b3.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)


- 如果一直throws。则会一直throw到JVM机，JVM机器处理异常的方式就是直接退出程序并输出异常的信息




- 调用抛出异常的方法的时候，要对该方法进行异常处理。
![在这里插入图片描述](https://img-blog.csdnimg.cn/69d6a6694b9948748364620f0dbf5a73.png?x-oss-process=image/watermark,type_ZHJvaWRzYW5zZmFsbGJhY2s,shadow_50,text_Q1NETiBATkpVU1RaSkM=,size_20,color_FFFFFF,t_70,g_se,x_16)

